apiVersion: apps/v1 # change version API
kind: ReplicaSet # change resource name
metadata:
  name: rs-hello-kube
spec:
  replicas: 2
  selector:
    matchLabels: # change here 
      app: hello-kube
    matchExpressions:
      - key: app
        operator: In # In, NotIn, Exists, DoesNotExist
        values:
          - kubia
  template:
    metadata:
      labels:
        app: hello-kube
    spec:
      containers:
      - image: hello-kube
        name: hello-kube
        ports:
          - containerPort: 3000
