version: "3"

services:
  db:
     image: mysql:5.7
     volumes:
       - db_data: /var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: abc.123
       MYSQL_DATABASE: wp-db
       MYSQL_USER: wp-user
       MYSQL_PASSWORD: abc@123
     networks:
       - net-local

  wordpress:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
       - wordpress_data:/var/www/html
     ports:
       - "8080:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_NAME: wp-db
       WORDPRESS_DB_USER: wp-user
       WORDPRESS_DB_PASSWORD: abc@123
     networks:
       - net-local
       - net-pro

  redis:
     image: redis
     networks:
       - net-local
     port:
       - "6379"

volumes:
  db_data: {}
  wordpress_data: {}

networks:
  net-local:
      driver: bridge
  net-pro:
      driver: bridge
